[package]
authors = ["Jorge Aparicio <jorge@japaric.io>", "Daniel Egger <daniel@eggers-club.de>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "HAL for the STM32F1xx family of microcontrollers"
keywords = ["arm", "cortex-m", "stm32", "hal"]
license = "MIT OR Apache-2.0"
name = "stm32f1xx-hal"
repository = "https://github.com/stm32-rs/stm32f1xx-hal"
documentation = "https://docs.rs/stm32f1xx-hal"
readme = "README.md"
edition = "2018"
version = "0.2.1"

[package.metadata.docs.rs]
features = ["stm32f103", "rt"]

[dependencies]
cortex-m = "0.5.8"
nb = "0.1.1"
cortex-m-rt = "0.6.7"
stm32f1 = "0.6.0"

[dependencies.void]
default-features = false
version = "1.0.2"

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.2"

[dev-dependencies]
panic-halt = "0.2.0"
panic-semihosting = "0.5.1"
panic-itm = "0.4.0"
# cortex-m-rtfm = "0.3.1"
cortex-m-semihosting = "0.3.2"
enc28j60 = "0.2.1"
heapless = "0.4.1"
m = "0.1.1"
mfrc522 = "0.2.0"
serde_derive = "1.0.87"

[dev-dependencies.byteorder]
default-features = false
version = "1.3.1"

[dev-dependencies.cobs]
default-features = false
version = "0.1.3"

[dev-dependencies.crc16]
default-features = false
version = "0.4.0"

[dev-dependencies.either]
default-features = false
version = "1.5.0"

#[dev-dependencies.jnet]
#git = "https://github.com/japaric/jnet"
#rev = "df96b408049ca952ad7844d6552e87cf8fc18d2a"

#[dev-dependencies.motor-driver]
#git = "https://github.com/japaric/motor-driver"
#rev = "00c8b15223643090d69f1acfb8b7a7a43a440417"

#[dev-dependencies.mpu9250]
#git = "https://github.com/japaric/mpu9250"
#rev = "8f9ecad690093cb71c41301ca5e5705706150610"

[dev-dependencies.serde]
default-features = false
version = "1.0.87"

#[dev-dependencies.serde-json-core]
#git = "https://github.com/japaric/serde-json-core"
#rev = "6f12b77c1ffeae167989fe06e0d8b15978bd6d18"

[features]
doc = []
rt = ["stm32f1/rt"]
stm32f100 = ["stm32f1/stm32f100", "all"]
stm32f103 = ["stm32f1/stm32f103", "all", "pwm"]
all   = ["bb", "delay", "pwm_input", "qei", "rtc", "tim1", "tim2", "tim3", "tim4", "gpioa", "gpiob", "gpioc", "usart1", "usart2", "spi1", "spi2", "i2c1", "i2c2", "dma1"]
afio  = ["gpio"]
bkp   = []
bb    = []
delay = []
dma   = []
gpio  = []
i2c   = ["afio"]
pwm   = ["timer", "afio"]
pwm_input = ["timer", "afio"]
qei   = ["afio"]
rtc   = ["bkp"]
serial = ["afio"]
spi   = ["afio"]
timer = []
gpioa = ["gpio"]
gpiob = ["gpio"]
gpioc = ["gpio"]
gpiod = ["gpio"]
gpioe = ["gpio"]
dma1  = ["dma"]
dma2  = ["dma"]
tim1 = []
tim2 = []
tim3 = []
tim4 = []
usart1 = ["serial"]
usart2 = ["serial"]
usart3 = ["serial"]
spi1 = ["spi"]
spi2 = ["spi"]
spi3 = ["spi"]
i2c1 = ["i2c"]
i2c2 = ["i2c"]

[profile.dev]
incremental = false
codegen-units = 1

[profile.release]
codegen-units = 1
debug = true
lto = true
